# Change default connection username, password and database.
# Specify also host and port if not using tnsnames.ora connection.
default:
  username: system
  password: oracle
  database: XE
  host: localhost
  port: 49161

# Add other connection if needed.
# You can access them with plsql(:other) where :other is connection name specified below.

# other:
#   username: scott
#   password: tiger
#   database: xe
